name: 'QPM Action'
description: 'Provides utilities for qpm CI'
author: 'Fernthedev'
inputs:
  publish:
    required: false
    description: 'Denotes if this will publish to QPM qpackages.com. Possible values are: "late", "now" or undefined. Late publish will only run if action ran with success'

  version:
    required: false
    description: 'Specifies version to publish. Requires publish'
  tag:
    required: false
    description: 'Specifies tag to use for github release. Defaults to version'

  restore:
    required: false
    description: 'Whether restore should be called. This will use the cache if possible'
    default: 'true'
  cache:
    required: false
    description: 'Specifies if the action should handle caches'
    default: 'true'

  cache_lockfile:
    required: false
    description: 'Specifies if the action should use caches with qpm.shared.json'
    default: 'true'

  qpm_release_bin:
    required: false
    description: 'Specifies the path for the release binary or debug if not specified'
    default: 'false'
  qpm_debug_bin:
    required: false
    description: 'Specifies the path for the debug binary'
    default: 'false'
  qpm_qmod:
    required: false
    description: 'Specifies the path for the qmod'

  workflow_token:
    required: false
    description: 'Specifies the workflow Github Secret Token required for some functionality'
  publish_token:
    required: false
    description: 'The token required for publishing to qpackages.com'

runs:
  using: node20
  main: dist/index.js    
  post: 'dist/post/index.js'
  post-if: success()
