name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  publish: # change this
    required: false
    description: 'Denotes if this will publish to QPM qpackages.com'
    default: 'false'
  version:
    required: false
    description: 'Specifies version to publish. Requires publish'
  upload_mode:
    required: false
    description: 'Specifies if the action should upload the binaries to Github release or artifact'
  workflow_token:
    required: false
    description: 'Specifies the workflow Github Secret Token required for some functionality'
runs:
  using: 'node16'
  main: 'dist/index.js'

