name: Test workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  test-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test workflow
        uses: ./
        with:
          workflow_token: ${{secrets.GITHUB_TOKEN}}
        # with:
        # milliseconds: 1000
